#!/bin/bash

# OmniFusion Music Website - Automatic Deployment Setup Script
# This script helps you set up automatic deployment to Vercel

echo "🚀 Setting up Automatic Deployment for OmniFusion Music Website"
echo "================================================================"

echo ""
echo "📋 Required Information:"
echo "========================"
echo "Project ID: prj_MUqdrwNsihv0Qg218MOOwgL1UaxC"
echo "Organization ID: inkfusion-labs-projects"
echo "GitHub Repository: https://github.com/inkFusionLabs/OmniFusionMusic-Website"
echo ""

echo "🔑 Step 1: Get Vercel Token"
echo "============================"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click on your profile (top right)"
echo "3. Go to Settings → Tokens"
echo "4. Click 'Create Token'"
echo "5. Name it: 'GitHub Actions Deploy'"
echo "6. Copy the token (you'll need it for Step 3)"
echo ""

echo "🌐 Step 2: Add GitHub Secrets"
echo "=============================="
echo "1. Go to: https://github.com/inkFusionLabs/OmniFusionMusic-Website/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add these secrets:"
echo ""
echo "   Name: VERCEL_TOKEN"
echo "   Value: [Your Vercel token from Step 1]"
echo ""
echo "   Name: VERCEL_ORG_ID"
echo "   Value: inkfusion-labs-projects"
echo ""
echo "   Name: VERCEL_PROJECT_ID"
echo "   Value: prj_MUqdrwNsihv0Qg218MOOwgL1UaxC"
echo ""

echo "🧪 Step 3: Test the Setup"
echo "=========================="
echo "1. Make a small change to your website"
echo "2. Commit and push:"
echo "   git add ."
echo "   git commit -m 'Test automatic deployment'"
echo "   git push origin main"
echo "3. Check GitHub Actions: https://github.com/inkFusionLabs/OmniFusionMusic-Website/actions"
echo "4. Your site should update automatically at: https://omni-fusion-music-website.vercel.app"
echo ""

echo "✅ Setup Complete!"
echo "=================="
echo "Your website will now automatically deploy to Vercel whenever you push to the main branch."
echo ""
echo "🌐 Live Site: https://omni-fusion-music-website.vercel.app"
echo "📊 GitHub Actions: https://github.com/inkFusionLabs/OmniFusionMusic-Website/actions"
echo ""
echo "Need help? Check DEPLOYMENT.md for detailed instructions." 